### ISSUE TITLE
Write only first line on file

### ISSUE THREAD

**Issue by flavico** [glynnbird/couchsnap#1]
We're try to use couchsnap but we found one problem, when couchsnap execute only the first line of the backup was on file. Looking the code of the couchsnap I think to solve this problem we're need to separate o treatment of json "docs" and "last_seq" of the return query of couchdb, look this line https://github.com/glynnbird/couchsnap/blob/c4a277eede0bbd327fce471f3c504e7922a72b42/changesreader.js#L52  
if in "readable" you treat as the same output using "jsonpour" or write only first line of backup or just de last_seq. You can see this problem and help us to solve. Thanks.

We're using couchdb v3.3.1, nodejs v16

**Comment by glynnbird** [comment]
I don't know what's going on with Node 16, but `couchsnap` works fine on Node 16 & 18. 

If you upgrade your node.js verison, it should work!

**Comment by flavico** [comment]
I tried now to use the following versions of node 16, 17, 18 and 19 in all didn't work for me, I dont know why.

**Comment by glynnbird** [comment]
what is your COUCH_URL? (without sharing credentials)

I just tried it with CouchDB like so:

```sh
export COUCH_URL='http://x:y@127.0.0.1:5984'
couchsnap --db users
```

(Notice I'm using `127.0.0.1` not `localhost`)

**Comment by flavico** [comment]
I 
did this

#node -v
v19.3.0

#npm install -g couchsnap
#export COUCH_URL='http://x:y@127.0.0.1:5984'
#couchsnap --db _global_changes
spooling changes for _global_changes since 0
_global_changes-snapshot-2023-04-19T16:02:50.187Z.jsonl
_global_changes-meta.json

_global_changes have 4 documents

a will attach the backup file here

![Captura de tela de 2023-04-19 13-08-43](https://user-images.githubusercontent.com/12112287/233135481-dcf81363-f6fb-4b84-bfae-4d3149427b99.png)

**Comment by glynnbird** [comment]
Aha I've never tried this with global changes. Can you try it with one
normal database name?

**Comment by flavico** [comment]
I've tried with other my databases, ocurr the same problem.

**Comment by carolinesweetpea** [comment]
I've got a similar issue - most of my databases only backup one line :( 
```
root@bd346a40ad27:/couchdb# couchsnap --db states
spooling changes for states since 0
states-snapshot-2023-05-14T10:23:00.108Z.jsonl
states-meta.json
root@bd346a40ad27:/couchdb# wc states-snapshot-2023-05-14T10\:23\:00.108Z.jsonl 
  1   1 131 states-snapshot-2023-05-14T10:23:00.108Z.jsonl

```
(`states` database has 4 documents in it).

(the one database I really care about doesn't even manage one line, and fails at this point
```root@bd346a40ad27:/couchdb# couchsnap --db <dbname> 
spooling changes for <dbname> since 0
Failed to spool changes from CouchDB
TypeError: buf.copy is not a function
```
but I suspect that's a separate issue - no `/_changes` url activity in the logs for that db)

**Comment by carolinesweetpea** [comment]
Note I've been trying Couchdb version 3.3.2 and 3.1.1, using node 16 (using the standard node docker container)

**Comment by carolinesweetpea** [comment]
Final comment :)  I've discovered you've also written `couchshapshot` which does appear to back up all my database successfully. That should do the trick. Many thanks for writing all these - it is most appreciated.

**Comment by glynnbird** [comment]
Thanks for reporting. I just can't reproduce the error. I've tried on Node 14,16,18. It just works (on my machine).

**Comment by glynnbird** [comment]
```
TypeError: buf.copy is not a function
```

Must be the culprit

**Comment by flavico** [comment]
I followed the same way, change the tool for `couchsnapshot` and works very well, thanks.

**Comment by glynnbird** [comment]
I have published v0.5.1 of couchsnap. If anyone having this problem could try to use this version, I would appreciate the feedback.

**Comment by flavico** [comment]
Now it works for me in node 19, congrats, thanks.

**Comment by carolinesweetpea** [comment]
I've tested. The database which wasn't snapshotting at all is now working, which is great. The other one which was only snapshotting one record is still doing that.
