### ISSUE TITLE
Couchsnap not snapshotting all the documents

### ISSUE THREAD

**Issue by carolinesweetpea** [glynnbird/couchsnap#3]
According to futon (and the _all_docs api request) my database has 25619 documents in it

The first snapshot I took had 25550 documents in it, so missing a few.

I repeated the the snapshot again, and no new documents were added.

I removed all the snapshot files, and re-ran the snapshot again - this time: 25575 documents.
Third try was 25583 documents
Fourth try: 25580

The snapshots were also missing different documents - so this isn't a consistently missing out the same documents.

I've manually examined some of the documents, and there doesn't appear to be anything remarkable about them. It's across all different types of documents too.

**Comment by carolinesweetpea** [comment]
I've checked the _changes api request, and that's returning the correct number of documents (once deletions are taken into account)

**Comment by carolinesweetpea** [comment]
I've done some more digging, and it looks like the culprit might be jsonpour. The correct number of documents are going into jsonpour, but coming out, into `changeProcessor`, there are fewer documents.

I've intercepted the stream as it enters jsonpour, and checked the numbers, and then compared that to the number of documented processed - which gives me the discrepency.

**Comment by glynnbird** [comment]
Thanks for all the testing. Much appreciated. It seems I didn't correctly detect that the data had finished been written to disk so a a random amount of documents (sometimes 0) were left out. I've made a fix and published 0.6.0
